# Site settings
title: Arduino Day | IFES
description: > # this means to ignore newlines until "baseurl:"
  Está chegando o Arduino Day 2019 Cachoeiro, um evento para reunir a comunidade local para discutir ideias e apresentar projetos que utilizem plataformas de prototipagem de baixo custo. Serão oferecidos minicursos, palestras e mostras de trabalhos. Fique atento à agenda com a programação e às atividades que requerem inscrição. Venha participar com a gente.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://arduinoday.ci.ifes.edu.br" # the base hostname & protocol for your site
author: "Labora"

# Build settings
markdown: kramdown
permalink: /:title/

exclude: ["Gemfile", "Gemfile.lock", "README.md"]