# Site settings
title: Arduino Day
description: > # this means to ignore newlines until "baseurl:"
  Está chegando o Arduino Day 2019 Cachoeiro, um evento para reunir a comunidade local para discutir ideias e apresentar projetos que utilizem plataformas de prototipagem de baixo custo. Serão oferecidos minicursos, palestras e mostras de trabalhos. Fique atento à programação. Venha participar com a gente.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://arduinoday19.gusson.org" # the base hostname & protocol for your site
author: "Labora"

# Build settings
markdown: kramdown
permalink: /:title/
google_maps_javascript_api_key: "AIzaSyCdvKiZ7dmgeAGH3GicFsgkMdG0VtZbTew"

# Contact info
contact:
  phone: (28) 3526-9033 | (28) 3526-9045
  email: arduinoday.ci@gmail.com
  address: Rodovia ES-482 (Cachoeiro-Alegre) - Fazenda Morro Grande, CEP 29311-970 - Cachoeiro de Itapemirim, ES - Brasil

plugins:
  - jekyll-seo-tag
  - jekyll-minifier

jekyll-minifier:
  preserve_php: true
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_comments: true
  remove_intertag_spaces: true
  remove_quotes: false
  compress_css: true
  compress_javascript: true
  simple_doctype: false
  remove_script_attributes: false
  remove_style_attributes: false
  remove_link_attributes: false
  remove_form_attributes: false
  remove_input_attributes: false
  remove_javascript_protocol: false
  remove_http_protocol: false
  remove_https_protocol: false
  preserve_line_breaks: false
  simple_boolean_attributes: false
  compress_js_templates: false
  preserve_patterns:
  uglifier_args:


exclude: ["Gemfile", "Gemfile.lock", "README.md"]